const makesValues = [
  { value: "all", label: "All" },
  { value: "buick", label: "Buick" },
  { value: "hummer", label: "HUMMER" },
  { value: "subaru", label: "Subaru" },
  { value: "mitsubishi", label: "Mitsubishi" },
  { value: "volvo", label: "Volvo" },
  { value: "nissan", label: "Nissan" },
  { value: "lincoln", label: "Lincoln" },
  { value: "gmc", label: "GMC" },
  { value: "hyundai", label: "Hyundai" },
  { value: "mini", label: "MINI" },
  { value: "bentley", label: "Bentley" },
  { value: "mercedes-benz", label: "Mercedes-Benz" },
  { value: "aston martin", label: "Aston Martin" },
  { value: "pontiac", label: "Pontiac" },
  { value: "lamborghini", label: "Lamborghini" },
  { value: "audi", label: "Audi" },
  { value: "bmw", label: "BMW" },
  { value: "chevrolet", label: "Chevrolet" },
  { value: "chrysler", label: "Chrysler" },
  { value: "kia", label: "Kia" },
  { value: "land", label: "Land" },
]

export default makesValues
